/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grp6OOPR212;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author jmallari
 */
public class adminMenu extends javax.swing.JFrame {
Connection con;
    Statement stmt,stmt2;
    ResultSet rs,rs2;
    public adminMenu() {
        initComponents();
        DoConnect();
    }
    
    public void DoConnect(){
        //method to connect to Database
        try{
           //method definition is always in main class
           String host="jdbc:derby://localhost:1527/dbSEE";
           String uName = "group6";
           String uPass = "oopr212123";
           //get host from Services>Server>Properties>Database URL
          con = DriverManager.getConnection(host, uName, uPass) ;
           //Connection con = DriverManager.getConnection(host, uName, uPass );
           
           //execute sql statement for displaying records
           //stmt =  con.createStatement();
          
           
        }
        catch(SQLException err){
            System.out.println(err.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        btnNew = new javax.swing.JButton();
        btnEval = new javax.swing.JButton();
        btnPastEval = new javax.swing.JButton();
        btnActive = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jButton4.setText("jButton4");

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(420, 300));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        btnNew.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNew.setText("New Event");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        getContentPane().add(btnNew);
        btnNew.setBounds(110, 140, 210, 25);

        btnEval.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEval.setText("Evaluate Event");
        btnEval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEvalActionPerformed(evt);
            }
        });
        getContentPane().add(btnEval);
        btnEval.setBounds(110, 170, 210, 25);

        btnPastEval.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPastEval.setText("View/Print Evaluated Events");
        btnPastEval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPastEvalActionPerformed(evt);
            }
        });
        getContentPane().add(btnPastEval);
        btnPastEval.setBounds(110, 200, 210, 25);

        btnActive.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnActive.setText("Ongoing Evaluation");
        btnActive.setEnabled(false);
        btnActive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActiveActionPerformed(evt);
            }
        });
        getContentPane().add(btnActive);
        btnActive.setBounds(110, 110, 210, 25);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADMIN MENU");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 80, 170, 22);

        btnLogOut.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLogOut.setText("LOG OUT");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogOut);
        btnLogOut.setBounds(110, 240, 210, 23);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grp6OOPR212/7db70f43414483.png"))); // NOI18N
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 0, 420, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
       
        new adminNew().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnEvalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEvalActionPerformed
        try{
            //check if there are any events at all
            stmt =  con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
               String evtCodeSQL = ("Select * FROM TBLEVENTS where evaluated = false");
               rs = stmt.executeQuery(evtCodeSQL);
               
               //if no events yet 
               if(rs.next()==false){
                    JOptionPane.showMessageDialog(this,"No events to evaluate. Create New Event first.","Evaluate Event",JOptionPane.ERROR_MESSAGE);
                     
                }
                
               //if there are events
                else{
                                       
                            try{
                    //check if there are any evaluated events
                                stmt2 =  con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
                                evtCodeSQL = ("Select * FROM TBLEVENTS WHERE activate = true");
                                rs2 = stmt2.executeQuery(evtCodeSQL);

                                if(rs2.next()==false){
                                new search().setVisible(true);
                                this.setVisible(false);
                            }
                        else{
                            JOptionPane.showMessageDialog(this,"An event is currently being evaluated.");
                        }
                
                            rs2.close();
                            stmt2.close();
        }
        catch(SQLException err){
            System.out.println(err);
        }
                }
                
                rs.close();
                stmt.close();
        }
        catch(SQLException err){
            System.out.println(err);
        }
       
       
    }//GEN-LAST:event_btnEvalActionPerformed

    private void btnPastEvalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPastEvalActionPerformed
        try{
            //check if there are any evaluated events
            stmt =  con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
               String evtCodeSQL = ("Select * FROM TBLEVENTS WHERE EVALUATED = true");
               rs = stmt.executeQuery(evtCodeSQL);
               
                if(rs.next()==false){
               JOptionPane.showMessageDialog(this,"There are no evaluated events yet.");
                }
                else{
                new evaluatedEvents().setVisible(true);
                }
                
                rs.close();
                stmt.close();
        }
        catch(SQLException err){
            System.out.println(err);
        }
       
    }//GEN-LAST:event_btnPastEvalActionPerformed

    private void btnActiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActiveActionPerformed
        new ongoingEvent().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnActiveActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //check if there is an active evaluation
        try{
          
           //select event details from tblevents from active event
            stmt =  con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
           String SQL = "SELECT * FROM GROUP6.TBLEVENTS WHERE ACTIVATE = true";
           rs = stmt.executeQuery(SQL);
           //count how many ratings there are
            rs.last();
            int count = rs.getRow();
           if(count>0){
               btnActive.setEnabled(true);
           }
           
           rs.close();
           stmt.close();
           
        }
        catch(SQLException err){
            System.out.println(err.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
       new welcome().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_btnLogOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActive;
    private javax.swing.JButton btnEval;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnPastEval;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    // End of variables declaration//GEN-END:variables
}
